remote_theme: pmarsceill/just-the-docs
#theme: "just-the-docs"
title: "Composerlib"
description: "Algorithmic Composition library for C++"

search_enabled: true

aux_links:
  "Composer on GitHub":
    - "//github.com/composernew/composerlib"
  "Composer on CodeDocs":
    - "https://codedocs.xyz/composernew/composerlib/"

aux_links_new_tab: false

footer_content: "Copyright &copy; Alan Freitas. Distributed by an <a href=\"https://github.com/alandefreitas/composer/tree/master/LICENSE.txt\">MIT license.</a>"
